resources:
  traefik-deployment:
    type: kubernetes:apps/v1:Deployment
    options:
      dependsOn:
      - ${docker-image-traefik}
    properties:
      metadata:
        namespace: ${k8s.namespace}
        name: ${names.pods.traefik}
        labels:
          app: ${names.pods.traefik}
      spec:
        replicas: ${traefik.replicas-nb}
        selector:
          matchLabels:
            app: ${names.pods.traefik}
        template:
          metadata:
            labels:
              app: ${names.pods.traefik}
          spec:
            serviceAccountName: ${names.service-accounts.traefik}
            containers:
              - name: ${names.containers.traefik}
                image: ${docker.build.registry}${docker.build.namespace}${traefik.image.repository}:${traefik.image.tag}
                args:
                  # provide: file
                  - --providers.file.directory=/file-provider
                  # provider: kubernetes
                  - --providers.kubernetesingress=true
                  - --providers.kubernetesingress.allowEmptyServices=true
                  - --providers.kubernetesingress.namespaces=${k8s.namespace}
                  # logging
                  - --log.level=${traefik.logging.level}
                  - --log.format=${traefik.logging.format}
                  - --accesslog
                  # letsencrypt resolver
                  - --certificatesresolvers.${traefik.tls-resolver-name}.acme.tlschallenge=true
                  - --certificatesresolvers.${traefik.tls-resolver-name}.acme.email=${acme.email}
                  - --certificatesresolvers.${traefik.tls-resolver-name}.acme.storage=${acme.storage}
                  - --certificatesresolvers.${traefik.tls-resolver-name}.acme.caserver=${acme.endpoint}
                  # entrypoints
                  - --entryPoints.${traefik.ports.https.name}.address=:${traefik.ports.https.targetPort}
