resources:
  # https://github.com/pulumi/pulumi-docker-build/blob/main/examples/yaml/Pulumi.yaml
  docker-image-traefik:
    type: docker-build:Image
    options:
      dependsOn:
      - ${docker-image-builder}
    properties:
      buildArgs:
        BUILDER_IMAGE: ${docker.images.registry}${docker.images.namespace}${image-builder.name}:${image-builder.tag}
        SOURCE_IMAGE: ${traefik.image.registry}${traefik.image.namespace}${traefik.image.repository}:${traefik.image.tag}
        JELLYFIN_CERT_RESOLVER: ${traefik.tls-resolver-name}
        JELLYFIN_ENTRYPOINT: ${traefik.ports.https.name}
        JELLYFIN_HOST: ${jellyfin.host}
        JELLYFIN_PORT: ${jellyfin.port}
        JELLYFIN_SERVICE_NAME: ${jellyfin.name}
        JELLYFIN_URL: ${urls.prefix}${jellyfin.name}${urls.suffix}.${domain}
      context:
        location: src/base/core/traefik/images
      dockerfile:
        location: src/base/core/traefik/images/Dockerfile
      platforms: ${docker.images.platforms}
      push: ${docker.images.push}
      registries: ${docker.registries}
      tags:
      - ${docker.images.registry}${docker.images.namespace}${traefik.image.repository}:${traefik.image.tag}
