resources:
  # https://www.pulumi.com/registry/packages/docker/api-docs/image/
  docker-image-traefik:
    type: docker:Image
    options:
      version: v4.5.0
    properties:
      registry:
        server: ${docker.registry.server}
        username: ${docker.registry.username}
        password: ${docker.registry.password}
      build:
        context: src/base/core/traefik/images
        dockerfile: src/base/core/traefik/images/Dockerfile
        platform: ${docker.images.platform}
        args:
          BUILDER_IMAGE: ${docker.images.registry}${docker.images.namespace}${image-builder.image.repository}:${image-builder.image.tag}
          SOURCE_IMAGE: ${traefik.image.registry}${traefik.image.namespace}${traefik.image.repository}:${traefik.image.tag}
          JELLYFIN_CERT_RESOLVER: ${traefik.tls-resolver-name}
          JELLYFIN_ENTRYPOINT: ${traefik.ports.https.name}
          JELLYFIN_HOST: ${jellyfin.host}
          JELLYFIN_PORT: ${jellyfin.port}
          JELLYFIN_SERVICE_NAME: ${jellyfin.name}
          JELLYFIN_URL: ${urls.prefix}${jellyfin.name}${urls.suffix}.${domain}
      imageName: ${docker.images.registry}${docker.images.namespace}${traefik.image.repository}:${traefik.image.tag}
      skipPush: ${docker.images.skip-push}
