resources:
  traefik-service:
    type: kubernetes:core/v1:Service
    options:
      dependsOn:
      - ${traefik-deployment}
    properties:
      metadata:
        namespace: ${k8s.namespace}
        name: ${names.services.traefik}

      spec:
        ports:
          - protocol: TCP
            port: ${traefik.ports.https.port}
            targetPort: ${traefik.ports.https.targetPort}
            name: ${traefik.ports.https.name}
        selector:
          app: ${names.pods.traefik}
        type: LoadBalancer
