resources:
  traefik-service-account:
    type: kubernetes:core/v1:ServiceAccount
    properties:
      metadata:
        namespace: ${k8s.namespace}
        name: ${k8s.service-accounts.prefix}${traefik.name}${k8s.service-accounts.suffix}
