resources:
  docker-registry-deployment:
    type: kubernetes:apps/v1:Deployment
    properties:
      metadata:
        namespace: ${k8s.namespace}
        name: ${names.pods.docker-registry}
        labels:
          app: ${names.pods.docker-registry}

      spec:
        selector:
          matchLabels:
            app: ${names.pods.docker-registry}
        template:
          metadata:
            labels:
              app: ${names.pods.docker-registry}
          spec:
            containers:
              - name: ${names.containers.docker-registry}
                image: ${docker-registry.image}
                ports:
                  - name: ${docker-registry.ports.http.name}
                    containerPort: ${docker-registry.ports.http.targetPort}
