resources:
  docker-registry-ingress:
    type: kubernetes:networking.k8s.io/v1:Ingress
    options:
      dependsOn:
      - ${docker-registry-service}
    properties:
      metadata:
        namespace: ${k8s.namespace}
        name: ${names.ingresses.docker-registry}
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: ${traefik.ports.https.name}
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.tls.certresolver: ${traefik.tls-resolver-name}
          pulumi.com/skipAwait: "true"

      spec:
        rules:
          - host: ${hosts.docker-registry}
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: ${names.services.docker-registry}
                      port:
                        number: ${docker-registry.ports.http.targetPort}

#outputs:
#  docker-registry--ip: ${docker-registry-ingress.status.loadBalancer.ingress[0].ip}
