resources:
  docker-registry-service:
    type: kubernetes:core/v1:Service
    options:
      dependsOn:
      - ${docker-registry-deployment}
    properties:
      metadata:
        namespace: ${k8s.namespace}
        name: ${names.services.docker-registry}

      spec:
        ports:
          - protocol: TCP
            name: ${docker-registry.ports.http.name}
            port: ${docker-registry.ports.http.targetPort}
        selector:
          app: ${names.pods.docker-registry}

#outputs:
#  docker-registry--port: ${docker-registry-service.spec.ports[0].port}
