resources:
  traefik-rbac-cluster-role-binding:
    type: kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding
    properties:
      metadata:
        name: ${names.role-bindings.traefik}
        namespace: ${k8s.namespace}
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: ${names.roles.traefik}
      subjects:
        - kind: ServiceAccount
          name: ${names.service-accounts.traefik}
          namespace: ${k8s.namespace}
