resources:
  whoami-deployment:
    type: kubernetes:apps/v1:Deployment
    properties:
      metadata:
        namespace: ${k8s.namespace}
        name: ${k8s.services.prefix}${whoami.name}${k8s.services.suffix}
        labels:
          app: ${k8s.services.prefix}${whoami.name}${k8s.services.suffix}

      spec:
        replicas: ${whoami.replicas-nb}
        selector:
          matchLabels:
            app: ${k8s.services.prefix}${whoami.name}${k8s.services.suffix}
        template:
          metadata:
            labels:
              app: ${k8s.services.prefix}${whoami.name}${k8s.services.suffix}
          spec:
            containers:
              - name: ${k8s.containers.prefix}${whoami.name}${k8s.containers.suffix}
                image: ${whoami.image}
                ports:
                  - name: ${whoami.ports.http.name}
                    containerPort: ${whoami.ports.http.targetPort}
