resources:
  homarr-deployment:
    type: kubernetes:apps/v1:Deployment
    options:
      dependsOn:
      - ${docker-image-homarr}
    properties:
      metadata:
        namespace: ${k8s.namespace}
        name: ${names.pods.homarr}
        labels:
          app: ${names.pods.homarr}
      spec:
        selector:
          matchLabels:
            app: ${names.pods.homarr}
        template:
          metadata:
            labels:
              app: ${names.pods.homarr}
          spec:
            containers:
            - name: ${names.containers.homarr}
              image: ${docker.build.registry}${docker.build.namespace}${homarr.image.repository}:${homarr.image.tag}
              env:
              - name: TZ
                value: ${timezone}
