resources:
  homarr-deployment:
    type: kubernetes:apps/v1:Deployment
    options:
      dependsOn:
      - ${docker-image-homarr}
    properties:
      metadata:
        namespace: ${k8s.namespace}
        name: ${k8s.services.prefix}${homarr.name}${k8s.services.suffix}
        labels:
          app: ${k8s.services.prefix}${homarr.name}${k8s.services.suffix}
      spec:
        selector:
          matchLabels:
            app: ${k8s.services.prefix}${homarr.name}${k8s.services.suffix}
        template:
          metadata:
            labels:
              app: ${k8s.services.prefix}${homarr.name}${k8s.services.suffix}
          spec:
            containers:
            - name: ${k8s.containers.prefix}${homarr.name}${k8s.containers.suffix}
              image: ${docker.images.registry}${docker.images.namespace}${homarr.image.repository}:${homarr.image.tag}
              env:
              - name: TZ
                value: ${timezone}
