resources:
  homarr-ingress:
    type: kubernetes:networking.k8s.io/v1:Ingress
    properties:
      metadata:
        namespace: ${k8s.namespace}
        name: ${k8s.ingresses.prefix}${homarr.name}${k8s.ingresses.suffix}
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: ${traefik.ports.https.name}
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.tls.certresolver: ${traefik.tls-resolver-name}
          pulumi.com/skipAwait: "true"

      spec:
        rules:
          - host: ${urls.prefix}${homarr.name}${urls.suffix}.${domain}
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: ${k8s.services.prefix}${homarr.name}${k8s.services.suffix}
                      port:
                        number: ${homarr.ports.http.targetPort}
