resources:
  homarr-service:
    type: kubernetes:core/v1:Service
    options:
      dependsOn:
      - ${homarr-deployment}
    properties:
      metadata:
        namespace: ${k8s.namespace}
        name: ${names.services.homarr}

      spec:
        ports:
          - protocol: TCP
            name: ${homarr.ports.http.name}
            port: ${homarr.ports.http.targetPort}
        selector:
          app: ${names.pods.homarr}
