http:
  routers:
    jellyfin-local:
      entryPoints:
      - ${JELLYFIN_ENTRYPOINT}
      tls:
        certResolver: ${JELLYFIN_CERT_RESOLVER}
      service: ${JELLYFIN_SERVICE_NAME}
      rule: Host(`${JELLYFIN_URL}`)
  services:
    jellyfin-local:
      loadBalancer:
        passHostHeader: false
        servers:
        - url: http://${JELLYFIN_HOST}:${JELLYFIN_PORT}
