variables:

  traefik:
    image:
      registry: docker.io/
      namespace: ""
      repository: traefik
      tag: v3.1
    logging:
      format: common
      level: DEBUG
    name: traefik
    ports:
      https:
        name: https
        port: 443
        targetPort: 443
    replicas-nb: 1
    tls-resolver-name: letsencrypt

  hosts:
    traefik: ${urls.prefix}${traefik.name}${urls.suffix}.${domain}

  names:
    containers:
      traefik: ${k8s.containers.prefix}${traefik.name}${k8s.containers.suffix}
    ingresses:
      traefik: ${k8s.ingresses.prefix}${traefik.name}${k8s.ingresses.suffix}
    pods:
      traefik: ${k8s.pods.prefix}${traefik.name}${k8s.pods.suffix}
    roles:
      traefik: ${k8s.roles.prefix}${traefik.name}${k8s.roles.suffix}
    role-bindings:
      traefik: ${k8s.role-bindings.prefix}${traefik.name}${k8s.role-bindings.suffix}
    services:
      traefik: ${k8s.services.prefix}${traefik.name}${k8s.services.suffix}
    service-accounts:
      traefik: ${k8s.service-accounts.prefix}${traefik.name}${k8s.service-accounts.suffix}
