variables:
  traefik:
    image:
      registry: docker.io/
      namespace: ""
      repository: traefik
      tag: v3.1
    logging:
      format: common
      level: DEBUG
    name: traefik
    ports:
      https:
        name: https
        port: 443
        targetPort: 443
    replicas-nb: 1
    tls-resolver-name: letsencrypt
